### ISSUE TITLE
Cryptpad Nginx - letsencrypt-webroot file not found errors in Log

### ISSUE THREAD

**Issue by joshua-russell** [xwiki-labs/cryptpad-docker#61] opened 2023-02-03 18:32 UTC
This is what I am seeing in the log:
```
nginx: [emerg] open() "/etc/nginx/letsencrypt-webroot" failed (2: No such file or directory) in /etc/nginx/conf.d/cryptpad.conf:12
```
This is running on a Synology NAS and the letsencrypt cert for this container renewed. I tried recreating the container but receive the same error. The log indicates a file or directory is missing, but I’m not sure what to do to fix this.

**Comment by promasu** [comment] 2023-02-03 18:42
duplicate of #58

**Closed by promasu** 2023-02-03 18:42 UTC
